import './Inventory.css';
import Header from '../../components/Header/Header';

const Inventory = () => {
  return (
    <div style={{ minHeight: '150vh', backgroundColor: '#E4D3FF' }}>
        <Header />
        <div style={{ display: 'flex', paddingTop: '100px' }}>
            {/* <div class="sine-wave"></div> */}
            {/* <p style={{}}>Search...</p>
            <img style={{ width: '1000px', paddingLeft: '300px' }} src={process.env.PUBLIC_URL + '/images/wave.png'} alt="Wave" /> */}
        </div>
        <div>
            <p>InventoryLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor sagittis dapibus. In eget ipsum orci. Ut ut metus odio. Suspendisse potenti. Nulla volutpat lectus ut ex sollicitudin, ac egestas mauris feugiat. Quisque efficitur eu arcu eget congue. Mauris volutpat elit non sollicitudin aliquet. Pellentesque ac sem eget enim lacinia sollicitudin id id turpis. Nulla elementum est at dolor pretium ullamcorper.</p>
            <p>InventoryNunc accumsan ipsum elit, id hendrerit sem vestibulum et. Praesent eu ligula vitae velit scelerisque malesuada. Vivamus rhoncus vulputate arcu ut suscipit. Aliquam erat volutpat. Duis varius dui at nibh eleifend, ac ultrices nisl tristique. Vivamus tempor iaculis cursus. Donec gravida fringilla odio. In hac habitasse platea dictumst.</p>
            <p>InventoryPhasellus mattis viverra felis, sed vulputate felis efficitur at. Aliquam eu facilisis lorem, sed aliquam velit. Sed ut sapien sed urna consectetur dignissim. Donec at lobortis ligula. Nullam varius velit vitae vestibulum vestibulum. Curabitur quis cursus ex, in luctus felis. Sed interdum fringilla dui sed tempor.</p>
            <p>InventoryLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor sagittis dapibus. In eget ipsum orci. Ut ut metus odio. Suspendisse potenti. Nulla volutpat lectus ut ex sollicitudin, ac egestas mauris feugiat. Quisque efficitur eu arcu eget congue. Mauris volutpat elit non sollicitudin aliquet. Pellentesque ac sem eget enim lacinia sollicitudin id id turpis. Nulla elementum est at dolor pretium ullamcorper.</p>
            <p>InventoryNunc accumsan ipsum elit, id hendrerit sem vestibulum et. Praesent eu ligula vitae velit scelerisque malesuada. Vivamus rhoncus vulputate arcu ut suscipit. Aliquam erat volutpat. Duis varius dui at nibh eleifend, ac ultrices nisl tristique. Vivamus tempor iaculis cursus. Donec gravida fringilla odio. In hac habitasse platea dictumst.</p>
            <p>InventoryPhasellus mattis viverra felis, sed vulputate felis efficitur at. Aliquam eu facilisis lorem, sed aliquam velit. Sed ut sapien sed urna consectetur dignissim. Donec at lobortis ligula. Nullam varius velit vitae vestibulum vestibulum. Curabitur quis cursus ex, in luctus felis. Sed interdum fringilla dui sed tempor.</p>
            <p>InventoryLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor sagittis dapibus. In eget ipsum orci. Ut ut metus odio. Suspendisse potenti. Nulla volutpat lectus ut ex sollicitudin, ac egestas mauris feugiat. Quisque efficitur eu arcu eget congue. Mauris volutpat elit non sollicitudin aliquet. Pellentesque ac sem eget enim lacinia sollicitudin id id turpis. Nulla elementum est at dolor pretium ullamcorper.</p>
            <p>InventoryNunc accumsan ipsum elit, id hendrerit sem vestibulum et. Praesent eu ligula vitae velit scelerisque malesuada. Vivamus rhoncus vulputate arcu ut suscipit. Aliquam erat volutpat. Duis varius dui at nibh eleifend, ac ultrices nisl tristique. Vivamus tempor iaculis cursus. Donec gravida fringilla odio. In hac habitasse platea dictumst.</p>
            <p>InventoryPhasellus mattis viverra felis, sed vulputate felis efficitur at. Aliquam eu facilisis lorem, sed aliquam velit. Sed ut sapien sed urna consectetur dignissim. Donec at lobortis ligula. Nullam varius velit vitae vestibulum vestibulum. Curabitur quis cursus ex, in luctus felis. Sed interdum fringilla dui sed tempor.</p>
            <p>InventoryLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor sagittis dapibus. In eget ipsum orci. Ut ut metus odio. Suspendisse potenti. Nulla volutpat lectus ut ex sollicitudin, ac egestas mauris feugiat. Quisque efficitur eu arcu eget congue. Mauris volutpat elit non sollicitudin aliquet. Pellentesque ac sem eget enim lacinia sollicitudin id id turpis. Nulla elementum est at dolor pretium ullamcorper.</p>
            <p>InventoryNunc accumsan ipsum elit, id hendrerit sem vestibulum et. Praesent eu ligula vitae velit scelerisque malesuada. Vivamus rhoncus vulputate arcu ut suscipit. Aliquam erat volutpat. Duis varius dui at nibh eleifend, ac ultrices nisl tristique. Vivamus tempor iaculis cursus. Donec gravida fringilla odio. In hac habitasse platea dictumst.</p>
            <p>InventoryPhasellus mattis viverra felis, sed vulputate felis efficitur at. Aliquam eu facilisis lorem, sed aliquam velit. Sed ut sapien sed urna consectetur dignissim. Donec at lobortis ligula. Nullam varius velit vitae vestibulum vestibulum. Curabitur quis cursus ex, in luctus felis. Sed interdum fringilla dui sed tempor.</p>
            <p>InventoryLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor sagittis dapibus. In eget ipsum orci. Ut ut metus odio. Suspendisse potenti. Nulla volutpat lectus ut ex sollicitudin, ac egestas mauris feugiat. Quisque efficitur eu arcu eget congue. Mauris volutpat elit non sollicitudin aliquet. Pellentesque ac sem eget enim lacinia sollicitudin id id turpis. Nulla elementum est at dolor pretium ullamcorper.</p>
            <p>InventoryNunc accumsan ipsum elit, id hendrerit sem vestibulum et. Praesent eu ligula vitae velit scelerisque malesuada. Vivamus rhoncus vulputate arcu ut suscipit. Aliquam erat volutpat. Duis varius dui at nibh eleifend, ac ultrices nisl tristique. Vivamus tempor iaculis cursus. Donec gravida fringilla odio. In hac habitasse platea dictumst.</p>
            <p>InventoryPhasellus mattis viverra felis, sed vulputate felis efficitur at. Aliquam eu facilisis lorem, sed aliquam velit. Sed ut sapien sed urna consectetur dignissim. Donec at lobortis ligula. Nullam varius velit vitae vestibulum vestibulum. Curabitur quis cursus ex, in luctus felis. Sed interdum fringilla dui sed tempor.</p>
            <p>InventoryLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor sagittis dapibus. In eget ipsum orci. Ut ut metus odio. Suspendisse potenti. Nulla volutpat lectus ut ex sollicitudin, ac egestas mauris feugiat. Quisque efficitur eu arcu eget congue. Mauris volutpat elit non sollicitudin aliquet. Pellentesque ac sem eget enim lacinia sollicitudin id id turpis. Nulla elementum est at dolor pretium ullamcorper.</p>
            <p>InventoryNunc accumsan ipsum elit, id hendrerit sem vestibulum et. Praesent eu ligula vitae velit scelerisque malesuada. Vivamus rhoncus vulputate arcu ut suscipit. Aliquam erat volutpat. Duis varius dui at nibh eleifend, ac ultrices nisl tristique. Vivamus tempor iaculis cursus. Donec gravida fringilla odio. In hac habitasse platea dictumst.</p>
            <p>InventoryPhasellus mattis viverra felis, sed vulputate felis efficitur at. Aliquam eu facilisis lorem, sed aliquam velit. Sed ut sapien sed urna consectetur dignissim. Donec at lobortis ligula. Nullam varius velit vitae vestibulum vestibulum. Curabitur quis cursus ex, in luctus felis. Sed interdum fringilla dui sed tempor.</p>
            <p>InventoryLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor sagittis dapibus. In eget ipsum orci. Ut ut metus odio. Suspendisse potenti. Nulla volutpat lectus ut ex sollicitudin, ac egestas mauris feugiat. Quisque efficitur eu arcu eget congue. Mauris volutpat elit non sollicitudin aliquet. Pellentesque ac sem eget enim lacinia sollicitudin id id turpis. Nulla elementum est at dolor pretium ullamcorper.</p>
            <p>InventoryNunc accumsan ipsum elit, id hendrerit sem vestibulum et. Praesent eu ligula vitae velit scelerisque malesuada. Vivamus rhoncus vulputate arcu ut suscipit. Aliquam erat volutpat. Duis varius dui at nibh eleifend, ac ultrices nisl tristique. Vivamus tempor iaculis cursus. Donec gravida fringilla odio. In hac habitasse platea dictumst.</p>
            <p>InventoryPhasellus mattis viverra felis, sed vulputate felis efficitur at. Aliquam eu facilisis lorem, sed aliquam velit. Sed ut sapien sed urna consectetur dignissim. Donec at lobortis ligula. Nullam varius velit vitae vestibulum vestibulum. Curabitur quis cursus ex, in luctus felis. Sed interdum fringilla dui sed tempor.</p>
            <p>InventoryLorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor sagittis dapibus. In eget ipsum orci. Ut ut metus odio. Suspendisse potenti. Nulla volutpat lectus ut ex sollicitudin, ac egestas mauris feugiat. Quisque efficitur eu arcu eget congue. Mauris volutpat elit non sollicitudin aliquet. Pellentesque ac sem eget enim lacinia sollicitudin id id turpis. Nulla elementum est at dolor pretium ullamcorper.</p>
            <p>InventoryNunc accumsan ipsum elit, id hendrerit sem vestibulum et. Praesent eu ligula vitae velit scelerisque malesuada. Vivamus rhoncus vulputate arcu ut suscipit. Aliquam erat volutpat. Duis varius dui at nibh eleifend, ac ultrices nisl tristique. Vivamus tempor iaculis cursus. Donec gravida fringilla odio. In hac habitasse platea dictumst.</p>
            <p>InventoryPhasellus mattis viverra felis, sed vulputate felis efficitur at. Aliquam eu facilisis lorem, sed aliquam velit. Sed ut sapien sed urna consectetur dignissim. Donec at lobortis ligula. Nullam varius velit vitae vestibulum vestibulum. Curabitur quis cursus ex, in luctus felis. Sed interdum fringilla dui sed tempor.</p>
        </div>
    </div>
  );
};

export default Inventory;
